language: node_js

node_js:
  - stable
  - v4
  - v5
  - v6
  - v7

sudo: false

cache:
  directories:
    - node_modules

env:
  global:
    - secure: DPZ1twm86o01f2xta0b8Z/Fu/KEH2bzxZBsLAtSymQIS7D5Dvu3EYe3zC0+71cewiKrVPGlC3p7k46AQIwBDLR/lNBIrarsDO5YUvRRp3SOlGX8JmOEKIzP5kQQ1bUcEhKcZXAJHrWhaa0CxzqbZRrFiRUUMlZSxcnMNa6mZ9kWPHAzNg8Imj24y+/oOfnDoIp3u5m8y+X85knvrTaD2o9lEs0t1PWjFsM9sHzxc3+o8zwyWvC3yPbloviXciYIhn2Q3XD+28kaltqEDHWl/cbikhqXcj2bZ7OGlVdGMq+4GF0Zcnw8YojoltypJ3dw2XM8QUeEbw+2S4UQyFg2stn3lfXde1dlKSaP9JzxA4oMHgWNZSGGotxl107pdQMDlYeIspkc03DQs3Nqd/l3//hSn5Po7r/qim0fTh+htoGZP8jkYH6byAbVvNIv3MxtFZMSb4jk+swKIQrLrTu33ssu3YoVtcKCS0kpTj3avaTa2LQOYH196CSqiWHaIuFMOhaccBYr/f/XeNTFXcISCcbVE/6cT3ZoQ2DNUr766Ysab+E+lYYW/98Wcyuhgxuc3MngDntrj31OAcnW+Wf00YxiHVlgFET4PcJZTt2x1QiujjejTxWuY2sQbsLtfuO0qTIlSAOuhcaKHJx4NvoZjVNyAXuXEVfDbpyACHZPQaGk=

script:
  - npm run lint
  - npm test

after_script:
  - npm run cover
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
  - cat coverage/lcov.info | node_modules/codeclimate-test-reporter/bin/codeclimate.js
