language: node_js

node_js:
  - stable
  - v4
  - v5
  - v6
  - v7

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    - secure: MBmDs7/uOYs1O8mxB/y+Qmw/KLe2Q603lk1kmEmICxWyBPaIdYBaNRBM6RVYdfvvSZVLqV7oEYXeiXRz52S1NB4+3AvXF2jPl6c8n1bAN+HUovvNNyvvB5rDakfg+9NJoU0gT8EjkhIjQ7llznDWR3hxK2+C+sRUFCKAhYxhwvNdukNipA7pDxxw7pxfYLZLFkzFbotBoLupKkntMK0hx5s3EQPTVqJTKrbPcjdqovjBrzlRlmLhXm+WzjnbVCBoDMRYo+k21iwXWcHmiQXhqo9hy/TzdgvHVGudJT4UgIDv2NFMh520CcO/koNRDus9RTlvGd1oQOTRV1p3Q3xjtzjvQOT7gaAPdlSNDXQxHZAbHAKpBn/ZXJ4yqiFPUEk1pRH5Qy/8i1WJpAJqyaRe8brg2RtU9Hx9/X6QlKinFbDgIGVIE4/frCbw0G6SeMA1BiuKV5J5+C7DAnGx1Aze61nVAM2h98nZxQPJn7MRDD8AHZkvtBsfCXwEaOyrVMlm4SeoRahtnP0end0/NkDp2tL95QXbepKd8G3CG3kIwoCP7qDRl7Zwkn0O6N5rhNklUE7aFPMsSXrIvlJi5byecdtTw/K3MzOuHOsQDWNOJp7sxdA7fbY7TbgSjlI75lQpUo8zHs0uHark2ZMQ09wDg7PmQ9zbemf8ETGJzHB5efw=
    - secure: h79zEztaS7IAwx/B8rww/sJWc+X3MEvAen8xE6hIPdWnYr94OM2HsJncQptsTELaMcAQWkyfe9DzCCduI/PP4Liot02G+hYeKPka2xovaTcsFPQpL8mnOeYhLk7U4XTNR4Y16LVb+oOo5N7LrJ1S5p3HT5OY/hJ86FUJStyaizmLzT561caktDlpaa90sgJ2RiC37rWaPx9Dl2kibU0dRs2JjNLcmxejVzxu/mvaChJynl+Afn8JBFb4q2vvJnDGi+8LVEuUFVYbVHQIWYV7ib2gCaYC2x5ZdYQAU2nlxXzmwmICMW8ObHT3riHFQ8CiUjeEp1MQg4zX3wDVi/RAhoVzYomFlauJBMfk2C8qoraOUPBTCBc1x6yLW88v8R0NYMYLveaZ8RJryKqj0hmc7B6ekWghNMpxvdJisBcYCUubQy4LSwQuJLU0bvQISvUqbqHpZfunnAGQKRJ9FuN8lrtTrMPN7quK7bMKu/7dWHDEmnAQE1TBq0hYPK3KKPMQMYNOkQCAx6+Zd1RHn284387jiiO9F2A5dxSO3kb2dqQr5JnyJiIY/G+4pTIn1ZqGDbWl0oDHWT9Mb+rcY9qEBpj3P1DNX6/JgjINmgYzPPbbyONUzkE/vndpY2U3VIcZn0ipt4naSEEVfUKacv8XorBSdnCvD+P0BqbJMPE9C4c=

script:
  - npm run lint
  - npm test

after_script:
  - npm run cover
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
  - cat coverage/lcov.info | node_modules/codeclimate-test-reporter/bin/codeclimate.js
