language: node_js

node_js:
  - 12
  - 11
  - 10
  - 8

sudo: false

cache: npm

env:
  global:
    - secure: MBmDs7/uOYs1O8mxB/y+Qmw/KLe2Q603lk1kmEmICxWyBPaIdYBaNRBM6RVYdfvvSZVLqV7oEYXeiXRz52S1NB4+3AvXF2jPl6c8n1bAN+HUovvNNyvvB5rDakfg+9NJoU0gT8EjkhIjQ7llznDWR3hxK2+C+sRUFCKAhYxhwvNdukNipA7pDxxw7pxfYLZLFkzFbotBoLupKkntMK0hx5s3EQPTVqJTKrbPcjdqovjBrzlRlmLhXm+WzjnbVCBoDMRYo+k21iwXWcHmiQXhqo9hy/TzdgvHVGudJT4UgIDv2NFMh520CcO/koNRDus9RTlvGd1oQOTRV1p3Q3xjtzjvQOT7gaAPdlSNDXQxHZAbHAKpBn/ZXJ4yqiFPUEk1pRH5Qy/8i1WJpAJqyaRe8brg2RtU9Hx9/X6QlKinFbDgIGVIE4/frCbw0G6SeMA1BiuKV5J5+C7DAnGx1Aze61nVAM2h98nZxQPJn7MRDD8AHZkvtBsfCXwEaOyrVMlm4SeoRahtnP0end0/NkDp2tL95QXbepKd8G3CG3kIwoCP7qDRl7Zwkn0O6N5rhNklUE7aFPMsSXrIvlJi5byecdtTw/K3MzOuHOsQDWNOJp7sxdA7fbY7TbgSjlI75lQpUo8zHs0uHark2ZMQ09wDg7PmQ9zbemf8ETGJzHB5efw=

script:
  - npm run lint
  - npm test

after_script:
  - npm run cover
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
